# Generated by Django 3.2.19 on 2023-06-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('open', models.BooleanField(default=False, verbose_name='Открытая команда')),
                ('invites', models.ManyToManyField(related_name='teams_invites', to=settings.AUTH_USER_MODEL, verbose_name='Приглашения')),
                ('members', models.ManyToManyField(related_name='teams_member', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_mentor', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
                ('teamlead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_teamlead', to=settings.AUTH_USER_MODEL, verbose_name='Тимлид')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
