# Generated by Django 3.2.19 on 2023-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_invites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
