# Generated by Django 3.2.19 on 2023-06-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_invite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='type',
            new_name='achieve_type',
        ),
    ]
