# Generated by Django 3.2.19 on 2023-06-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_type_achievement_achieve_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='type',
            new_name='skill_type',
        ),
    ]
