# Generated by Django 3.2.19 on 2023-06-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_type_skill_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='file',
        ),
    ]
