# Generated by Django 3.2.19 on 2023-06-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_achievement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(to='users.Achievement', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_organization', to='users.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='users_skill', to='users.Skill', verbose_name='Навыки'),
        ),
    ]
