# Generated by Django 3.2.19 on 2023-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230613_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
    ]
