# Generated by Django 3.2.18 on 2023-09-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20230908_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сфера',
                'verbose_name_plural': 'Сферы',
            },
        ),
        migrations.CreateModel(
            name='IncomingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Входящая заявка',
                'verbose_name_plural': 'Входящие заявки',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='OutgoingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Исходящая заявка',
                'verbose_name_plural': 'Исходящие заявки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('open', models.BooleanField(default=True, verbose_name='Вакансия открыта')),
                ('skills', models.ManyToManyField(blank=True, related_name='vacancies_skill', to='users.Skill', verbose_name='Навык')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacancies_speciality', to='users.speciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_branch', to='projects.branch', verbose_name='Сфера')),
                ('incoming_applications', models.ManyToManyField(blank=True, related_name='projects_incoming_application', to='projects.IncomingApplication', verbose_name='Входящие заявки')),
                ('members', models.ManyToManyField(blank=True, related_name='projects_members', to='projects.Member', verbose_name='Участники')),
                ('outcoming_applications', models.ManyToManyField(blank=True, related_name='projects_outcoming_application', to='projects.OutgoingApplication', verbose_name='Исходящие заявки')),
                ('teamlead', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тимлид')),
                ('vacancies', models.ManyToManyField(blank=True, related_name='projects_vacancy', to='projects.Vacancy', verbose_name='Вакансии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='outgoingapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_applications_project', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='outgoingapplication',
            name='user_to',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='outgoingapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_applications_vacancy', to='projects.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='member',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members_vacancy', to='projects.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='incomingapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_applications_vacancy', to='projects.vacancy', verbose_name='Вакансия'),
        ),
    ]
