# Generated by Django 3.2.18 on 2023-09-23 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.Project.get_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='outgoingapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_applications_project', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='outgoingapplication',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_applications_user', to='users.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outgoingapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_applications_vacancy', to='projects.vacancy', verbose_name='Вакансия'),
        ),
    ]
