# Generated by Django 3.2.18 on 2023-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230923_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация'),
        ),
    ]
