# Generated by Django 3.2.18 on 2023-09-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_member_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='annotation',
        ),
        migrations.AddField(
            model_name='incomingapplication',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация'),
        ),
    ]
