# Generated by Django 3.2.18 on 2023-09-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230923_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='outcoming_applications',
            new_name='outgoing_applications',
        ),
    ]
