# Generated by Django 3.2.19 on 2023-06-15 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_teamlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='projects_invites', to=settings.AUTH_USER_MODEL, verbose_name='Приглашения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups_member', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
